version: '3.8'

services:
  # 主应用服务
  mindmap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindmap-qoder-app
    restart: unless-stopped
    ports:
      - "8080:80"     # 前端服务 (nginx)
      - "3001:3000"   # 后端服务 (node.js)
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # 可选：持久化日志
      - ./logs:/var/log/nginx
    networks:
      - mindmap-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：Redis缓存（用于会话管理）
  redis:
    image: redis:7-alpine
    container_name: mindmap-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - mindmap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  mindmap-network:
    driver: bridge

volumes:
  redis-data:
    driver: local